AllCops:
  NewCops: enable
  Exclude:
    - 'bin/*'
    - 'node_modules/node-sass/src/libsass/extconf.rb'
    - 'node_modules/node-sass/src/libsass/contrib/libsass.spec'
    - 'config/initializers/devise.rb'
    - 'db/schema.rb'
    - 'db/migrate/20210609143530_devise_create_users.rb'


# Customize rules
Style/FrozenStringLiteralComment:
  Enabled: false
Style/Documentation:
  Enabled: false
Style/ClassAndModuleChildren:
  Enabled: false
Metrics/MethodLength:
  Max: 15
Metrics/CyclomaticComplexity:
  Max: 10
Metrics/PerceivedComplexity:
  Max: 10
Style/GlobalStdStream:
  Enabled: false
Metrics/BlockLength:
  Max: 26
